version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - products
      - auth

  products:
    build: ./products
    container_name: products
    env_file:
      - .env
    ports:
      - "5022:5022"
    depends_on:
      - db

  auth:
    build: ./auth
    container_name: auth
    env_file:
      - .env
    ports:
      - "5012:5012"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
