version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - products
      - auth
      - activity
      - user_measurements
      - service1

  products:
    build: ./products
    container_name: products
    env_file:
      - .env
    ports:
      - "5022:5022"
    depends_on:
      - db

  achievements:
    build: ./achievements
    container_name: achievements
    env_file:
      - .env
    ports:
      - "5023:5023"
    depends_on:
      - db
      - products

  auth:
    build: ./auth
    container_name: auth
    env_file:
      - .env
    ports:
      - "5012:5012"
    depends_on:
      - db

  activity:
    build: ./activity
    container_name: activity
    env_file:
      - .env
    ports:
      - "5013:5013"
    depends_on:
      - db

  user_measurements:
    build: ./user_measurements
    container_name: user_measurements
    env_file:
      - .env
    ports:
      - "5014:5014"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  service1:
    build: ./service1
    container_name: service1
    expose:
      - "5001"

  user_goals:
    build: ./user_goals
    container_name: user_goals_service
    env_file:
      - .env
    ports:
      - "5015:5015"
    depends_on:
      - db


volumes:
  postgres_data:
